### PR TITLE
Added instructions for including jni libs

### PR DESCRIPTION
**Pull request by Pesegato**

### CODE REVIEW

**Comment by FibreFoX** [comment]
@Pesegato have you checked using `additionalAppResources` ?

**Comment by Pesegato** [comment]
No, and have no idea on what it does... documentation for this parameter?

**Comment by FibreFoX** [comment]
There is an example for this: https://github.com/FibreFoX/javafx-gradle-plugin/tree/master/examples/additional-application-files

**Comment by Pesegato** [comment]
I'll try and see what happens, but is not clear where the bundled files are placed... inside the application JAR? On the same folder of the EXE?
Besides, the whole "some installers" concept sounds a bit like hit or miss... Please don't get me wrong, this project is awesome but I'd rather use simple but predictable and well documented tools rather than complex stuff with lots of undocumented options.
The purpouse of my pull request is to put visibility to a solution that I've found after checking on internet and asking on the gradle forum for 2 days... and finding out almost by accident.

**Comment by Pesegato** [comment]
Tried that. It put the file on the wrong folder "app", but it needs to go on the same folder of the executable (unless you tweak the java.library.path, but I think my proposed solution is simpler and cleaner)

**Comment by FibreFoX** [comment]
I prefer the "java.library.path"-solution, because when being delivered inside "app"-folder, this will work on non-native-bundle too. Some users do not use the installer-bundles, nor the native launchers.

This can be configured: https://github.com/FibreFoX/javafx-gradle-plugin/blob/24a0493f2e29ebd013a82c8d04a83d2a454d7c4b/src/main/java/de/dynamicfiles/projects/gradle/plugins/javafx/tasks/workers/JfxJarWorker.java#L179

The given solution wouldn't work for both. As I'm working on some mayor changes, this will get mentioned in some real documentation.

**Pull request closed without merging**
